import { LmsDataStore } from './contracts.js';
import { createPasswordCredentials } from './auth-utils.js';

const publishedOfferingIds: string[] = [];

function createStudentProfile(name: string, email: string, age: number, contactNumber: string, address: string): LmsDataStore['students'][number]['profile'] {
  return {
    name,
    email,
    idNumber: '',
    age,
    contactNumber,
    address,
    department: 'General',
    jobTitle: 'Not set',
    joined: 'January 2026',
    learningStreak: '8 days',
    profileImageDataUrl: null,
    profileImageUrl: null,
    passwordUpdatedAt: 'Not updated yet',
  };
}

function createMentorshipProfile(name: string, surname: string): LmsDataStore['students'][number]['mentorshipProfile'] {
  return {
    menteeName: name,
    menteeSurname: surname,
    menteeJobTitle: '',
    menteeQualification: '',
    menteeExperience: '',
    mentorName: '',
    mentorSurname: '',
    mentorJobTitle: '',
    mentorQualification: '',
    mentorExperience: '',
  };
}

function createMentorshipObjectives(): LmsDataStore['students'][number]['mentorshipObjectives'] {
  return {
    mentorshipGoals: [{ title: '', date: '', achievementDate: '' }],
    objectives: [{ title: '', date: '', achievementDate: '' }],
  };
}

function createMentorshipProgressReport(): LmsDataStore['students'][number]['mentorshipProgressReport'] {
  return {
    dateOfMeeting: '',
    objectivesAchieved: [{ objectiveAchieved: '', dateAchieved: '' }],
    mentorComments: '',
  };
}

function createStudentSettings(): LmsDataStore['students'][number]['settings'] {
  return {
    notificationPreferences: {
      emailUpdates: true,
      smsAlerts: false,
      assignmentReminders: true,
      messageNotifications: true,
      certificateMilestones: true,
    },
    privacySettings: {
      tutorProfileVisibility: true,
      classmateProfileVisibility: false,
      showEmailAddress: false,
      showContactNumber: false,
    },
    themePreference: 'ocean',
  };
}

function createAuthAccounts(): LmsDataStore['authAccounts'] {
  const administratorPassword = createPasswordCredentials('admin');
  const managerPassword = createPasswordCredentials('manager');
  const studentPassword = createPasswordCredentials('student');

  return [
    {
      id: 'auth-administrator',
      role: 'administrator',
      username: 'admin',
      email: 'admin@skillsconnect.app',
      route: '/admin-profile',
      passwordHash: administratorPassword.passwordHash,
      passwordSalt: administratorPassword.passwordSalt,
    },
    {
      id: 'auth-training-manager',
      role: 'training-manager',
      username: 'manager',
      email: 'ava.mokoena@skillsconnect.app',
      route: '/training-manager-profile',
      passwordHash: managerPassword.passwordHash,
      passwordSalt: managerPassword.passwordSalt,
    },
    {
      id: 'auth-student',
      role: 'student',
      username: 'student',
      email: 'alice.johnson@skillsconnect.app',
      route: '/student-profile',
      passwordHash: studentPassword.passwordHash,
      passwordSalt: studentPassword.passwordSalt,
      linkedStudentId: 'student-1',
    },
  ];
}

export function createDefaultData(): LmsDataStore {
  return {
    offerings: [],
    students: [
      {
        id: 'student-1',
        name: 'Alice',
        surname: 'Johnson',
        group: 'Group A',
        dateEnrolled: '2026-03-04',
        deadlineDate: '2026-04-24',
        email: 'alice.johnson@skillsconnect.app',
        jobTitle: 'Operations Coordinator',
        idNumber: '9201140082081',
        activeStatus: 'Active',
        department: 'Operations',
        lineManager: 'Nandi Khumalo',
        status: 'In Progress',
        assignedOfferingIds: [],
        role: 'student',
      isAdmin: false,
        profile: createStudentProfile('Alice Johnson', 'alice.johnson@skillsconnect.app', 19, '+27 71 555 0134', '24 Cedar Avenue, Johannesburg'),
        badgeState: { earnedBadgeIds: [] },
        settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Alice', 'Johnson'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [
          {
            id: 'notification-welcome',
            badge: 'New',
            title: 'Welcome to SkillsConnect',
            body: 'Start your learning journey by exploring your assigned courses and upcoming milestones.',
            dateLabel: '1 day ago',
            unread: true,
          },
        ],
        messages: [],
      },
      {
        id: 'student-2',
        name: 'Brian',
        surname: 'Molefe',
        group: 'Group B',
        dateEnrolled: '2026-02-18',
        deadlineDate: '2026-04-20',
        email: 'brian.molefe@skillsconnect.app',
        jobTitle: 'Customer Success Specialist',
        idNumber: '9007285476086',
        activeStatus: 'Active',
        department: 'Customer Success',
        lineManager: 'Thato Ncube',
        status: 'Completed',
        assignedOfferingIds: [],
        role: 'student',
      isAdmin: false,
        profile: createStudentProfile('Brian Molefe', 'brian.molefe@skillsconnect.app', 27, '+27 71 555 0135', '8 Olive Street, Pretoria'),
        badgeState: { earnedBadgeIds: [] },
        settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Brian', 'Molefe'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [],
        messages: [],
      },
      {
        id: 'student-3',
        name: 'Chloe',
        surname: 'Peters',
        group: 'Group A',
        dateEnrolled: '2026-03-27',
        deadlineDate: '2026-05-02',
        email: 'chloe.peters@skillsconnect.app',
        jobTitle: 'Finance Administrator',
        idNumber: '9403051186080',
        activeStatus: 'Inactive',
        department: 'Finance',
        lineManager: 'Michael Petersen',
        status: 'Not Yet Started',
        assignedOfferingIds: [],
        role: 'student',
      isAdmin: false,
        profile: createStudentProfile('Chloe Peters', 'chloe.peters@skillsconnect.app', 24, '+27 71 555 0136', '16 Pine Road, Cape Town'),
        badgeState: { earnedBadgeIds: [] },
          settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Chloe', 'Peters'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [],
        messages: [],
      },
      {
        id: 'student-4',
        name: 'Daniel',
        surname: 'Naidoo',
        group: 'Group C',
        dateEnrolled: '2026-01-30',
        deadlineDate: '2026-05-02',
        email: 'daniel.naidoo@skillsconnect.app',
        jobTitle: 'People Operations Partner',
        idNumber: '8806125031089',
        activeStatus: 'Active',
        department: 'People Operations',
        lineManager: 'Lerato Singh',
        status: 'Completed',
        assignedOfferingIds: [],
        role: 'student',
      isAdmin: false,
        profile: createStudentProfile('Daniel Naidoo', 'daniel.naidoo@skillsconnect.app', 29, '+27 71 555 0137', '11 Acorn Close, Durban'),
        badgeState: { earnedBadgeIds: [] },
          settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Daniel', 'Naidoo'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [],
        messages: [],
      },
      {
        id: 'student-5',
        name: 'Ella',
        surname: 'Dlamini',
        group: 'Group B',
        dateEnrolled: '2026-03-21',
        deadlineDate: '2026-04-20',
        email: 'ella.dlamini@skillsconnect.app',
        jobTitle: 'Sales Consultant',
        idNumber: '9509190248084',
        activeStatus: 'Active',
        department: 'Sales',
        lineManager: 'Kabelo Maduna',
        status: 'Not Yet Started',
        assignedOfferingIds: [],
        role: 'student',
      isAdmin: false,
        profile: createStudentProfile('Ella Dlamini', 'ella.dlamini@skillsconnect.app', 22, '+27 71 555 0138', '57 Market Lane, Johannesburg'),
        badgeState: { earnedBadgeIds: [] },
          settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Ella', 'Dlamini'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [],
        messages: [],
      },
      {
        id: 'student-6',
        name: 'Farai',
        surname: 'Khosa',
        group: 'Group C',
        dateEnrolled: '2026-02-06',
        deadlineDate: '2026-04-24',
        email: 'farai.khosa@skillsconnect.app',
        jobTitle: 'Systems Support Analyst',
        idNumber: '9102216354082',
        activeStatus: 'Active',
        department: 'IT',
        lineManager: 'Ayanda Maseko',
        role: 'student',
      isAdmin: false,
        status: 'Completed',
        assignedOfferingIds: [],
        profile: createStudentProfile('Farai Khosa', 'farai.khosa@skillsconnect.app', 25, '+27 71 555 0139', '44 Willow Crescent, Midrand'),
        badgeState: { earnedBadgeIds: [] },
          settings: createStudentSettings(),
        mentorshipProfile: createMentorshipProfile('Farai', 'Khosa'),
        mentorshipObjectives: createMentorshipObjectives(),
        mentorshipProgressReport: createMentorshipProgressReport(),
        notifiedOfferingIds: [...publishedOfferingIds],
        courses: [],
        notifications: [],
        messages: [],
      },
    ],
    trainingManagers: [],
    managerMessages: [],
    mentorshipAssignments: [],
    assignmentSubmissions: [],
    mentorshipSubmissions: [],
    quizSubmissions: [],
    externalTrainingRequests: [],
    branding: {
      themeId: 'ocean',
      companyLogoDataUrl: null,
    },
    authAccounts: createAuthAccounts(),
    passwordResetTokens: [],
    updatedAt: new Date().toISOString(),
  };
}